feat/RLCF-23:  Property data updated with i18n
labyes24/RK-LP-CAIO-FELIPE pull request #17
Opened 2024-06-13 19:34 UTC by Villa-Nova

2024-06-13 19:36 UTC, silvasouzaadriano approved these changes

2024-06-13 20:42 UTC, dam450 requested changes
a quantidade de imóveis está divergente
tem um a menos em espanhol

2024-06-14 16:46 UTC, ThalytaRangel approved these changes

2024-06-14 20:41 UTC, dam450 approved these changes

2024-06-14 21:11 UTC, Villa-Nova commented
@lab-yes O Adriano já tinha aprovado essa PR, porém cliquei sem querer para ele revisar novamente.

2024-06-14 21:11 UTC, merged